{
 "title": "Master接口展示",
 "time": { "from": "2023-03-24T06:18:37.747Z", "to": "2023-03-24T06:23:05.168Z" },
 "panels": [
  {
   "title": "自动运维任务",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- select count(ip) as 离线,status from iplists where status != 'online';\n\nselect count(taskid) as 自动巡检任务总数 from tasks WHERE $__timeFilter(Tasktime)"
    },
    {
     "rawSql": "select count(taskid) as 成功 from tasks WHERE $__timeFilter(Tasktime) and Taskstatus = \"ok\""
    },
    {
     "rawSql": "select count(taskid) as 异常 from tasks WHERE $__timeFilter(Tasktime) and Taskstatus != \"ok\""
    }
   ]
  },
  {
   "title": "Agent运行情况",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(ip) as 离线,status from iplists where status != 'online';"
    },
    {
     "rawSql": "select count(ip) as 在线,status from iplists where status = 'online';"
    }
   ]
  },
  {
   "title": "Agent在线列表",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "select ip from iplists where status = 'online';"
    }
   ]
  },
  {
   "title": "正常调用量地址Top10",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT path, COUNT(*) AS count FROM gins WHERE $__timeFilter(timex) and status_code=200 GROUP BY path  ORDER BY count DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "后端处理时间/s ",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT path, MAX(timeconsuming) AS max_time FROM gins WHERE $__timeFilter(timex) and path != '/master/keep/alive' and path != '/master/file/create' GROUP BY path ORDER BY max_time DESC LIMIT 10;\n"
    }
   ]
  },
  {
   "title": "Agent离线列表",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "rawSql": "select ip from iplists where status != 'online';"
    }
   ]
  },
  {
   "title": "Master调用趋势/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timex) AS \"time\",\n  COUNT(status_code) AS 异常访问\nFROM \n  spider.gins\n  WHERE status_code!=200 AND  $__timeFilter(timex)\nGROUP BY\n  timex\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(timex) AS \"time\",\n  COUNT(status_code) AS 正常访问\nFROM \n  spider.gins\n  WHERE status_code = '200' AND  $__timeFilter(timex)\nGROUP BY\n  timex\n"
    }
   ]
  },
  {
   "title": "异常调用量地址Top10",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT path, COUNT(*) AS count FROM gins WHERE $__timeFilter(timex) and status_code!=200 GROUP BY path  ORDER BY count DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Api成功率",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(status_code) AS 正常访问\nFROM \n  spider.gins\n  WHERE status_code=200 AND  $__timeFilter(timex)\n\n"
    },
    {
     "rawSql": "SELECT\n  COUNT(status_code) AS 异常\nFROM \n  spider.gins\n  WHERE status_code !=200 AND  $__timeFilter(timex)\n\n"
    }
   ]
  },
  {
   "title": "自动运维任务-异常",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "-- select count(ip) as 离线,status from iplists where status != 'online';\n\nselect taskid,Fromip as 来源IP,taskname as 任务名称,Taskstatus as 任务状态,datafrom as 数据来源,taskresult as 数据结果,alerttype as 初筛模式,alert_data as 匹配值,alertmethod as 告警模块,Tasktime as 上报时间 from tasks WHERE $__timeFilter(Tasktime) and Taskstatus != 'ok'"
    }
   ]
  }
 ]
}